Only coerce 1 column 2D outputs to Series for `predict*`/`fit_predict` methods (#8512)
For legacy reasons, cuml will coerce a 1 column 2D output to a Series instead of a DataFrame when outputting pandas/cudf types. In the long run we want to deprecate and remove this (See #7893).

However, the output of `transform`/`fit_transform`/`inverse_transform`/... should _always_ be a 2D output. Returning a 1D output from `transform` breaks the sklearn interface and makes it harder for sklearn to mix with cuml transformers.

```python
In [1]: import cuml                                                                                                                                                                          
                                                                                                                                                                                  
In [2]: import numpy as np                                                                                                                                                                   
                                                                                                                                                                                             
In [3]: import pandas as pd                                                                                                                                                                  
                                                                                                                                                                                             
In [4]: X = pd.DataFrame({"x": [0.5, 0.6, 0.7]})                                                                                                                                             
                                                                                                                                                                                             
In [5]: y = pd.Series([1.0, 2.0, 3.0])                                                                                                                                                       
                                                                                                                                                                                             
In [6]: from sklearn.pipeline import Pipeline                                                                                                                                                
                                                                                                                                                                                             
In [7]: pipe = Pipeline([("scaler", cuml.preprocessing.StandardScaler()), ("est", cuml.LinearRegression())])                                                                                                                                                                       
                                                                                                                                                                                             
In [8]: pipe.fit(X, y)
---------------------------------------------------------------------------                                                                                                                  
ValueError
...
ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature
) instead.
```

Viewing this behavior as a bug, we disable this coercion for most methods, only leaving it for `predict*`/`fit_predict` (which often treats 1D and 2D-1col the same).

A few reasons I think we should make this change as _breaking_ (rather than part of a deprecation):

- The current behavior is arguably a bug (at least for `transform`/`fit_transform`). `cuml` tries to implement the sklearn interface. The sklearn interface requires `X` to be a 2D array-like. `transform`/`fit_transform` are expected to return 2D array-like values.
- Unlike other inference methods (like `predict`), `transform`/`fit_transform` have ways in sklearn itself to return a dataframe-like output (e.g. `set_output`). We should strive for alignment in this case. Since `predict` lacks such a feature (and can thus never be hit by stock sklearn code) changing the behavior there feels a bit less urgent.
- In _most_ cases the output of `transform` should have multiple columns. It's only in the rare case that a transformer returns a single column array, and usually those are to then be fed into meta-estimators like `ColumnTransformer` where the individual outputs are stitched together into a larger feature matrix. Most estimators will have multiple feature inputs. As such, I expect this to break very little directly user-facing code, but will help our transformers work better with sklearn's compositional estimators (`Pipeline`, `FeatureUnion`, `ColumnTransformer`, ...).

Part of #7893.

Authors:
  - Jim Crist-Harif (https://github.com/jcrist)

Approvers:
  - Tim Head (https://github.com/betatim)

URL: https://github.com/NVIDIA/cuml/pull/8512